# This is a basic workflow to help you get started with Actions
name: Pre-Release

# Controls when the workflow will run
on:
  push:
    branches: [ develop ]
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ master ]

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Build and Pre-Release APK"
  releases:
    name: Build and Pre-Release APK
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Get packages
        run: flutter packages get

      - name: Build APK
        run: flutter build apk --split-per-abi

      - name: Pre-release APK
        uses: actions/upload-artifact@v2
        with:
          name: APKS
          path: build/app/outputs/flutter-apk/*.apk